spring.application.name=json-payment-service
### Konfigurasi Koneksi Database Neon
spring.datasource.url=jdbc:postgresql://${NEON_HOST}/${NEON_DB}?sslmode=require&channelBinding=require
spring.datasource.username=${NEON_USERNAME}
spring.datasource.password=${NEON_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

### Konfigurasi JPA & Hibernate
# agar springboot mengecek dan membuat table otomatis
spring.jpa.hibernate.ddl-auto=update

# agar otomatis ngeprint query SQL di console untuk debugging
spring.jpa.show-sql=true

# Dialect PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect