spring.application.name=json-payment-service
### Konfigurasi Koneksi Database Neon
spring.datasource.url=${DB_URL_PAYMENT}
spring.datasource.username=${DB_USER_PAYMENT}
spring.datasource.password=${DB_PASS_PAYMENT}
spring.datasource.driver-class-name=org.postgresql.Driver

### Konfigurasi JPA & Hibernate
# agar springboot mengecek dan membuat table otomatis
spring.jpa.hibernate.ddl-auto=update

# agar otomatis ngeprint query SQL di console untuk debugging
spring.jpa.show-sql=true

# Dialect PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${JWT_SECRET}

# Production port
server.port=8081

# Internal Service Key
app.internal.service-key=${INTERNAL_SERVICE_KEY}